# Generated by Django 3.1.1 on 2021-07-13 05:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('destination_type', models.CharField(choices=[('Trekking', 'Trekking'), ('Safari', 'Safari'), ('Island', 'Island'), ('More', 'More')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('tour_descr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('popular', models.BooleanField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
