# Generated by Django 3.1.1 on 2021-07-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tour',
            new_name='Destination',
        ),
    ]
