# Generated by Django 3.1.1 on 2021-07-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
